name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  logger: ^2.0.2+1
  google_fonts: 6.1.0
  syncfusion_flutter_charts: ^26.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #    - family: Satoshi
  #      fonts:
  #        - asset: assets/fonts/Satoshi-Variable.ttf
  #        - asset: assets/fonts/Satoshi-VariableItalic.ttf